- name: Ubuntu server general packages instalations
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install a package (e.g., tree)
      apt:
        name: tree
        state: present
    - name: Install pip
      apt:
        name: python3-pip
        state: latest
    - name: Install pipx
      apt:
        name: pipx
        state: present
    - name: Install python3-venv
      apt:
        name: python3-venv
        state: present
    - name: Install poetry
      apt:
        name: python3-poetry
        state: latest

- name: Installs with pipx
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Ensure pipx bin dir is in path.
      command: pipx ensurepath
    - name: Install poetry using pipx
      command: pipx install poetry
- name: Database installations
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Install SQLite
      apt:
        name: sqlite3
        state: latest
    - name: Install redis
      apt:
        name: redis
        state: latest
